# Generated by Django 5.2.6 on 2025-09-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Наименование сбора",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание сбора"),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="collect/", verbose_name="Обложка сбора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время создания сбора",
                    ),
                ),
                (
                    "stop_date",
                    models.DateTimeField(
                        verbose_name="Дата и время завершения сбора"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Активность сбора",
                    ),
                ),
                (
                    "event_format",
                    models.CharField(
                        choices=[("online", "Онлайн"), ("offline", "Офлайн")],
                        verbose_name="Формат встречи",
                    ),
                ),
                (
                    "event_reason",
                    models.CharField(
                        choices=[
                            ("date_birth", "День рождения"),
                            ("wedding", "Свадьба"),
                            ("company_party", "Корпоратив"),
                        ],
                        verbose_name="Вид события",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="Дата встречи")),
                ("event_time", models.TimeField(verbose_name="Время встречи")),
                (
                    "event_place",
                    models.TextField(verbose_name="Место проведения встречи"),
                ),
                (
                    "min_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Минимальная сумма платежа",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Целевая сумма сбора",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Общая цель сбора сбора",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
                "default_related_name": "collects",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Сумма платежа",
                    ),
                ),
                (
                    "hide_amount",
                    models.BooleanField(
                        default=False, verbose_name="Скрыть сумма платежа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время платежа"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.collect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
                "default_related_name": "payments",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк",
                "verbose_name_plural": "Лайки",
                "default_related_name": "likes",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(verbose_name="Текст комментария"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время комментария",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "default_related_name": "comments",
            },
        ),
    ]
