# Generated by Django 5.2.6 on 2025-09-13 02:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Активность сбора"
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="collect/", verbose_name="Обложка сбора"
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="min_payment",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Минимальная сумма платежа",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Целевая сумма сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Общая цель сбора сбора",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сумма платежа",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("author", "payment"), name="unique_like"
            ),
        ),
    ]
