# Generated by Django 5.2.6 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_collect_is_active_alter_collect_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="collect/",
                verbose_name="Обложка сбора",
            ),
        ),
    ]
